import streamlit as st
import pydeck as pdk
from backend.climate_processor import ClimateProcessor
from frontend.components.atlas_renderer import InteractiveAtlasRenderer

def render_climate_zones(ds, controls):
    """Renders the World Climate Zones intelligence map."""
    st.markdown("""
    <div class="section-tag">
        <span class="tag-line" style="background:linear-gradient(90deg,#10b981,#3b82f6)"></span>
        <h3 style="margin:0; font-size:1.25rem;">Global Domain Classification — World Climate Zones</h3>
    </div>
    <p style="color:#475569; font-size:0.92rem; margin-bottom:1.5rem;">
        Regions classified by solar intensity and thermal profiles derived from the active dataset.
    </p>
    """, unsafe_allow_html=True)

    col_map, col_legend = st.columns([4, 1])

    with col_legend:
        st.markdown("""
        <div style="background:rgba(56,189,248,0.05); border:1px solid rgba(56,189,248,0.2); 
                    border-radius:12px; padding:1rem; margin-bottom:1rem;">
            <div style="font-size:0.7rem; font-weight:700; color:#38bdf8; text-transform:uppercase; letter-spacing:0.1em;">
                Atmospheric Logic
            </div>
            <div style="font-size:0.75rem; color:#64748b; margin-top:0.4rem; line-height:1.4;">
                Data-driven zones based on Köppen-Geiger principles applied to {title}.
            </div>
        </div>
        """.format(title=ds.attrs.get('title', 'Global Observations')), unsafe_allow_html=True)
        
        InteractiveAtlasRenderer.render_climate_zone_legend()

    with col_map:
        with st.spinner("Classifying Planetary Domains..."):
            df_zones = ClimateProcessor.classify_climate_zones(ds)
        
        if df_zones.empty:
            st.error("Classification engine failed to process dataset.")
            return

        # Calculate centering for regional data
        # Ensure we use plain python floats to avoid PyDeck serialization errors
        avg_lat = float(df_zones['lat'].mean())
        avg_lon = float(df_zones['lon'].mean())
        
        # Render with PyDeck for high-performance hex/scatter map
        view_state = pdk.ViewState(
            latitude=avg_lat, 
            longitude=avg_lon, 
            zoom=2.5 if len(df_zones) < 10000 else 1.1, 
            pitch=0
        )

        layer = pdk.Layer(
            "ScatterplotLayer",
            df_zones,
            get_position=["lon", "lat"],
            get_fill_color="color_rgb",
            radius_min_pixels=4, # Increased
            radius_max_pixels=15, # Increased
            pickable=True
        )

        r = pdk.Deck(
            layers=[layer],
            initial_view_state=view_state,
            map_style="mapbox://styles/mapbox/dark-v9",
            tooltip={"text": "Zone: {zone}\nLat: {lat}\nLon: {lon}"}
        )

        st.pydeck_chart(r, use_container_width=True, height=500)

    st.markdown("""
    <div style="margin-top:2rem; padding:1.5rem; background:rgba(30,41,59,0.3); border-radius:12px; border-left:4px solid #38bdf8;">
        <div style="font-weight:700; color:#e2e8f0; margin-bottom:0.5rem;">Intelligence Summary</div>
        <div style="font-size:0.85rem; color:#94a3b8; line-height:1.6;">
            This dynamic classification map is generated by analyzing the long-term mean temperature and latitudinal band of every grid point in the NASA MERRA-2 / ERA5 dataset. 
            Unlike static maps, this reacts to the specific range and resolution of your injected data, providing a scientific baseline for regional anomaly analysis.
        </div>
    </div>
    """, unsafe_allow_html=True)
